package cmd

import (
	"context"
	"fmt"
	"io"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/nlink-jp/voice-studio-mcp/internal/config"
	"github.com/nlink-jp/voice-studio-mcp/internal/engine"
)

var (
	licensesTOML bool
	licensesFull string
)

var licensesCmd = &cobra.Command{
	Use:   "licenses",
	Short: "Collect voice-model license declarations for human review",
	Long: `Collect the author-declared license information embedded in installed AIVM
voice models (via the engine's /aivm_models endpoint) and help you turn it
into reviewed [[speaker_metadata]] config entries.

Workflow (ADR-0008 — collection is automated, verification stays human):
  1. voice-studio-mcp licenses                 # overview table
  2. voice-studio-mcp licenses --full <uuid>   # read the full license text
  3. voice-studio-mcp licenses --toml          # skeleton for config.toml
  4. paste the skeleton, fix license_url / commercial_use, remove the REVIEW
     note once you have actually read and accepted the terms`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, _, err := resolveConfig(configPath)
		if err != nil {
			return err
		}
		client := engine.NewClient(cfg.Engine.URL,
			time.Duration(cfg.Engine.RequestTimeoutSeconds)*time.Second)
		sup := engine.NewSupervisor(client, nil, engine.SupervisorOpts{
			Mode:            cfg.Engine.Mode,
			Command:         cfg.Engine.Command,
			Args:            cfg.Engine.Args,
			StartupTimeout:  time.Duration(cfg.Engine.StartupTimeoutSeconds) * time.Second,
			ShutdownTimeout: time.Duration(cfg.Engine.ShutdownTimeoutSeconds) * time.Second,
		})
		ctx := cmd.Context()
		if err := sup.Start(ctx); err != nil {
			return err
		}
		defer func() { _ = sup.Stop(context.Background()) }()

		switch {
		case licensesFull != "":
			return licensesFullText(ctx, cmd.OutOrStdout(), client, licensesFull)
		case licensesTOML:
			return licensesSkeleton(ctx, cmd.OutOrStdout(), client, cfg)
		default:
			return licensesTable(ctx, cmd.OutOrStdout(), client, cfg)
		}
	},
}

// licenseRow is one speaker's collected state.
type licenseRow struct {
	Speaker      engine.Speaker
	Manifest     *engine.AivmManifest // nil when no AIVM declaration exists
	DeclaredText string               // per-speaker policy, falling back to the manifest license
	Verified     *config.SpeakerMetadata
}

// collectRows joins /speakers, /aivm_models, and the config registry.
func collectRows(ctx context.Context, client *engine.Client, cfg *config.Config) ([]licenseRow, error) {
	speakers, err := client.Speakers(ctx)
	if err != nil {
		return nil, err
	}
	manifests := map[string]*engine.AivmManifest{}
	declaredTexts := map[string]string{}
	if models, err := client.AivmModels(ctx); err == nil {
		for _, model := range models {
			m := model.Manifest
			for _, sp := range model.Speakers {
				manifests[sp.Speaker.SpeakerUUID] = &m
				declaredTexts[sp.Speaker.SpeakerUUID] = model.LicenseTextFor(sp)
			}
		}
	}
	rows := make([]licenseRow, 0, len(speakers))
	for _, sp := range speakers {
		rows = append(rows, licenseRow{
			Speaker:      sp,
			Manifest:     manifests[sp.SpeakerUUID],
			DeclaredText: declaredTexts[sp.SpeakerUUID],
			Verified:     cfg.MetadataFor(sp.SpeakerUUID),
		})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].Speaker.Name < rows[j].Speaker.Name })
	return rows, nil
}

func (r licenseRow) declaredName() string {
	return engine.LicenseNameFromText(r.DeclaredText)
}

func (r licenseRow) status() string {
	switch {
	case r.Verified != nil:
		return "verified"
	case r.declaredName() != "":
		return "declared"
	default:
		return "unverified"
	}
}

func licensesTable(ctx context.Context, out io.Writer, client *engine.Client, cfg *config.Config) error {
	rows, err := collectRows(ctx, client, cfg)
	if err != nil {
		return err
	}
	counts := map[string]int{}
	fmt.Fprintf(out, "%-12s %-22s %-38s %s\n", "STATUS", "SPEAKER", "SPEAKER_UUID", "DECLARED LICENSE")
	for _, r := range rows {
		st := r.status()
		counts[st]++
		declared := r.declaredName()
		if r.Manifest != nil {
			if credit := r.Manifest.CreditLine(); credit != "" && declared != "" {
				declared += "  (credit: " + credit + ")"
			}
		}
		if st == "verified" {
			declared = r.Verified.License
		}
		fmt.Fprintf(out, "%-12s %-22s %-38s %s\n", st, clip(r.Speaker.Name, 22), r.Speaker.SpeakerUUID, declared)
	}
	fmt.Fprintf(out, "\n%d verified / %d declared / %d unverified\n",
		counts["verified"], counts["declared"], counts["unverified"])
	if counts["declared"]+counts["unverified"] > 0 {
		fmt.Fprintln(out, "Next: read the terms (licenses --full <speaker_uuid>), then generate config entries (licenses --toml).")
	}
	return nil
}

func licensesSkeleton(ctx context.Context, out io.Writer, client *engine.Client, cfg *config.Config) error {
	rows, err := collectRows(ctx, client, cfg)
	if err != nil {
		return err
	}
	today := time.Now().Format("2006-01-02")
	emitted := 0
	fmt.Fprintf(out, "# [[speaker_metadata]] skeleton generated by `voice-studio-mcp licenses --toml` (%s)\n", today)
	fmt.Fprintln(out, "# Entries are collected from AIVM manifests, NOT verified. For each entry:")
	fmt.Fprintln(out, "#   1. read the full terms: voice-studio-mcp licenses --full <speaker_uuid>")
	fmt.Fprintln(out, "#   2. fill license_url (AivisHub model page) and commercial_use")
	fmt.Fprintln(out, "#   3. delete the REVIEW note once you have accepted the terms")
	for _, r := range rows {
		if r.Verified != nil {
			continue // already reviewed; don't emit duplicates
		}
		license, credit := r.declaredName(), ""
		if r.Manifest != nil {
			credit = r.Manifest.CreditLine()
		}
		if credit == "" {
			credit = "AivisSpeech:" + r.Speaker.Name
		}
		fmt.Fprintf(out, "\n[[speaker_metadata]]\n")
		fmt.Fprintf(out, "speaker_uuid = %q\n", r.Speaker.SpeakerUUID)
		fmt.Fprintf(out, "name = %q\n", r.Speaker.Name)
		fmt.Fprintf(out, "license = %q\n", license)
		fmt.Fprintf(out, "license_url = \"\"\n")
		fmt.Fprintf(out, "credit = %q\n", credit)
		fmt.Fprintf(out, "commercial_use = false\n")
		fmt.Fprintf(out, "notes = %q\n", "REVIEW: auto-collected from the AIVM manifest on "+today+"; terms not yet reviewed by a human")
		emitted++
	}
	if emitted == 0 {
		fmt.Fprintln(out, "\n# All installed speakers already have reviewed [[speaker_metadata]] entries.")
	}
	return nil
}

func licensesFullText(ctx context.Context, out io.Writer, client *engine.Client, speakerUUID string) error {
	models, err := client.AivmModels(ctx)
	if err != nil {
		return err
	}
	for _, model := range models {
		for _, sp := range model.Speakers {
			if sp.Speaker.SpeakerUUID != speakerUUID && model.Manifest.UUID != speakerUUID {
				continue
			}
			m := model.Manifest
			fmt.Fprintf(out, "Model:    %s (aivm uuid %s)\n", m.Name, m.UUID)
			fmt.Fprintf(out, "Speaker:  %s (%s)\n", sp.Speaker.Name, sp.Speaker.SpeakerUUID)
			if len(m.Creators) > 0 {
				fmt.Fprintf(out, "Creators: %s\n", strings.Join(m.Creators, " / "))
			}
			if m.Description != "" {
				fmt.Fprintf(out, "\n--- description ---\n%s\n", strings.TrimSpace(m.Description))
			}
			if text := strings.TrimSpace(model.LicenseTextFor(sp)); text == "" {
				fmt.Fprintln(out, "\n--- license ---\n(no license text embedded in the manifest)")
			} else {
				fmt.Fprintf(out, "\n--- license (full text) ---\n%s\n", text)
			}
			return nil
		}
	}
	return fmt.Errorf("no installed model matches speaker/model uuid %q (see `voice-studio-mcp licenses`)", speakerUUID)
}

func clip(s string, n int) string {
	r := []rune(s)
	if len(r) <= n {
		return s
	}
	return string(r[:n-1]) + "…"
}

func init() {
	licensesCmd.Flags().BoolVar(&licensesTOML, "toml", false,
		"Emit a [[speaker_metadata]] config skeleton for unreviewed speakers")
	licensesCmd.Flags().StringVar(&licensesFull, "full", "",
		"Print the full declared license text for one speaker uuid (or AIVM model uuid)")
	rootCmd.AddCommand(licensesCmd)
}
